[package]
name = "pqmagic-sys"
version = "0.1.0"
edition = "2021"
description = "FFI Bindings to PQMagic"
authors = ["Kh05ifr4nD <meandSSH0219@gmail.com>"]
license = "Apache-2.0 OR MIT"
links = "pqmagic_std"
rust-version = "1.77.2"
repository = "https://github.com/Kh05ifr4nD/PQMagician"

include = [
    "build.rs",
    "PQMagic/CMakeLists.txt",
    "PQMagic/hash",
    "PQMagic/include",
    "PQMagic/kem",
    "PQMagic/LICENSE",
    "PQMagic/sig",
    "PQMagic/utils",
    "README.md",
    "src/lib.rs",
]

[build-dependencies]
cmake = "0.1.*"
const-str = "0.6.*"

[features]
default = ["kem", "sig", "vendor"]

adv = []
vendor = []

kem = ["aigis_enc", "kyber", "ml_kem"]
aigis_enc = []
kyber = []
ml_kem = []

sig = ["aigis_sig", "dilithium", "ml_dsa", "slh_dsa", "sphincs_a"]
aigis_sig = []
dilithium = []
ml_dsa = []
slh_dsa = []
sphincs_a = []

shake = []
sm3 = []
