on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Run weekly to catch upstream PQMagic changes
    - cron: "0 0 * * 0"

name: CI

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint_and_fmt:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace --all-targets --features=shake,sm3 --profile test -- -D warnings
  bd_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: stable
            update-submodule: true
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update PQMagic submodule
        if: matrix.update-submodule
        run: |
          git submodule update --remote --recursive
          echo "Updated PQMagic to latest commit"
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Build workspace
        run: cargo build --workspace --all-targets --features=shake,sm3
      - name: Run tests
        run: cargo test --workspace
      - name: Run doc tests
        run: cargo test --doc --workspace --features=shake,sm3
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build documentation
        run: cargo doc --workspace --features=shake,sm3 --no-deps
  ci-success:
    name: CI success
    runs-on: ubuntu-latest
    needs: [lint_and_fmt, bd_and_test, docs]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.lint_and_fmt.result }}" == "success" && \
                "${{ needs.bd_and_test.result }}" == "success" && \
                "${{ needs.docs.result }}" == "success" ]]; then
            echo "✅ All CI jobs passed!"
          else
            echo "❌ Some CI jobs failed:"
            echo "  Lint and Format: ${{ needs.lint_and_fmt.result }}"
            echo "  Build/Test: ${{ needs.bd_and_test.result }}"
            echo "  Documentation: ${{ needs.docs.result }}"
            exit 1
          fi
