on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Run weekly to catch upstream PQMagic changes
    - cron: "0 0 * * 0"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint_and_fmt:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace --all-targets --features=shake,sm3 --profile test -- -D warnings
  bd_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: stable
            update-submodule: true
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update PQMagic submodule
        if: matrix.update-submodule
        run: |
          git submodule update --remote --recursive
          echo "Updated PQMagic to latest commit"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace --all-targets --features=shake,sm3
      - run: cargo test --workspace
      - run: cargo test --doc --workspace --features=shake,sm3
  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --workspace --features=shake,sm3 --no-deps
